#ifndef COMMAND_KEYS_H_
#define COMMAND_KEYS_H_

#define COMMAND_CREATE_DATABASE 1
#define COMMAND_CREATE_TABLE 2
#define COMMAND_DELETE_DATABASE 3
#define COMMAND_DELETE_TABLE 4
#define COMMAND_OPEN_DATABASE_CONNECTION 5
#define COMMAND_CLOSE_DATABASE_CONNECTION 6
#define COMMAND_INSERT_INTO_TABLE 7
#define COMMAND_SELECT 8

#endif